# Generated by Django 3.2.19 on 2023-08-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(blank=True, to='products.ProductTag'),
        ),
    ]
